version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: app-mentallize
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./prisma/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - development
  
  app:
    build:
      context: .
      dockerfile: Development.Dockerfile
    ports:
      - "80:3000"
      - "5555:5555"
    volumes:
      - .:/app
    networks:
      - development
    depends_on:
      - db

networks:
  development:
    driver: bridge