version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: app-mentallize
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - development
  
  app:
    build:
      context: .
      dockerfile: Production.Dockerfile
    ports:
      - "3000:3000"

